'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import './admin.css';
import Notifications from './notifications';
type Conversation = {id:string;preview:string;updated:number;count:number;unread:number};
type Turn = {id:string;question:string;answer:string;status:string;created:number;updated:number};
const date = (n:number) => new Date(n).toLocaleString('zh-CN');
export default function Admin() {
 const [signed,setSigned]=useState(false),[checking,setChecking]=useState(true),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [items,setItems]=useState<Conversation[]>([]),[turns,setTurns]=useState<Turn[]>([]),[selected,setSelected]=useState(''),[q,setQ]=useState(''),[offset,setOffset]=useState(0),[more,setMore]=useState(false);
 const selection=useRef('');
 async function api<T = {items: Conversation[]; more: boolean}>(path:string,method='GET',data?:object){const r=await fetch('/api/admin/'+path,{method,headers:method==='GET'?{}:{'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined,cache:'no-store'});const b=await r.json() as T & {error?:string};if(r.status===401){setSigned(false);setItems([]);setTurns([]);}if(!r.ok)throw new Error(b.error||'操作失败');return b;}
 async function list(start=offset,query=q){const b=await api('conversations?'+new URLSearchParams({q:query,offset:String(start)}));setItems(b.items);setMore(b.more);setOffset(start);setSigned(true);}
 // This is an intentional one-time authentication probe when the private tool opens.
 // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
 useEffect(()=>{list(0,'').catch(()=>{}).finally(()=>setChecking(false));},[]);
 async function open(id:string){selection.current=id;setSelected(id);setTurns([]);setError('');try{const b=await api<{items:Turn[]}>('conversations/'+id);if(selection.current!==id)return;setTurns(b.items);await api('conversations/'+id,'POST',{action:'read',through:Math.max(0,...b.items.map((t:Turn)=>t.updated))});await list();}catch(e){setError((e as Error).message);}}
 async function run(action:()=>Promise<void>){setError('');setBusy(true);try{await action();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(checking)return <main className="admin-login">正在打开管理台…</main>;
 if(!signed)return <main className="admin-login"><form onSubmit={e=>{e.preventDefault();void run(async()=>{await api('login','POST',{password});setPassword('');await list(0,'');});}}><p className="admin-eyebrow">TIMI / PRIVATE STUDIO</p><h1>对话管理台</h1><p>查看工作室访客与数字分身的聊天。</p><label htmlFor="password">管理密码</label><input id="password" type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<p role="alert">{error}</p>}<button disabled={busy}>{busy?'正在登录…':'进入管理台 →'}</button><Link href="/">返回工作室</Link></form></main>;
 return <main className="admin-app"><header><div><p className="admin-eyebrow">TIMI / PRIVATE STUDIO</p><h1>访客对话</h1></div><div><span>保存最近 30 天</span><button disabled={busy} onClick={()=>void run(async()=>{await api('logout','POST',{});setSigned(false);setItems([]);setTurns([]);setSelected('');})}>退出登录</button></div></header><Notifications onOpen={id=>void open(id)} onRefresh={()=>{void list().catch(()=>{});}} onExpired={()=>{setSigned(false);setItems([]);setTurns([]);setError('登录已过期，请重新登录以继续接收提醒。');}}/>{error&&<p className="admin-error" role="alert">{error}</p>}<div className="admin-grid"><aside><form onSubmit={e=>{e.preventDefault();void run(()=>list(0));}}><input aria-label="搜索对话" placeholder="搜索问题或回答…" value={q} onChange={e=>setQ(e.target.value)}/><button disabled={busy}>搜索</button></form><button className="admin-refresh" disabled={busy} onClick={()=>void run(async()=>{await list();if(selected)await open(selected);})}>↻ 刷新记录</button><div className="admin-list">{items.length===0?<p className="admin-empty">暂无对话。新聊天会出现在这里。</p>:items.map(c=><button key={c.id} className={selected===c.id?'selected':''} onClick={()=>void open(c.id)}><span><time>{date(c.updated)}</time>{c.unread>0&&<b>{c.unread} 未读</b>}</span><strong>{c.preview}</strong><small>{c.count} 轮对话 · {c.id.slice(0,8)}</small></button>)}</div><nav><button disabled={!offset||busy} onClick={()=>void run(()=>list(Math.max(0,offset-50)))}>上一页</button><span>第 {offset/50+1} 页</span><button disabled={!more||busy} onClick={()=>void run(()=>list(offset+50))}>下一页</button></nav></aside><section className="admin-detail">{selected?<><div className="admin-detail-head"><span>访客 · {selected.slice(0,8)}</span><button disabled={busy} onClick={()=>{if(window.confirm('永久删除这段对话？'))void run(async()=>{await api('conversations/'+selected,'DELETE');selection.current='';setSelected('');setTurns([]);await list();});}}>删除对话</button></div><div className="admin-transcript">{turns.length===0?<p>正在读取，或此对话已清理。</p>:turns.map(t=><article key={t.id}><time>{date(t.created)}</time><div className="visitor"><small>访客</small><p>{t.question}</p></div><div className="assistant"><small>Timi · AI</small><p>{t.answer||(t.status==='pending'?'等待模型回答…':t.status==='cancelled'?'访客已停止回答':'本轮未能生成回答')}</p></div></article>)}</div></>:<div className="admin-placeholder"><span>✦</span><h2>听听大家聊了什么</h2><p>从左侧选择一段对话。<br/>只显示记录功能上线后的聊天。</p></div>}</section></div></main>;
}
